### ISSUE TITLE
Think about makefile

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2-book#17]
* So we could bind to cmd + shift + B in Rstudio

Here are a couple of example make files from other projects:

```
HTML_FILES := $(patsubst %.md, %.html, $(shell find . -name '*.md'  \! -name 'navbar.md'))

all: $(HTML_FILES)

$(HTML_FILES): %.html: %.md navbar.html ../template.html
	pandoc '$<' -o '$@' --smart --template ../template.html --include-before navbar.html

navbar.html: navbar.md
	pandoc '$<' -o '$@' --smart

.PHONY: clean
clean:
	$(RM) $(HTML_FILES)
```

* https://github.com/rstudio/dygraphs/blob/gh-pages/Makefile

**Comment by cpsievert** [comment]
Makefile is introduced with 781291c607bd0c09037507db9ac9fd0c6a22ffbd

This won't compile a website (do we want that capability eventually?), but compiles the pdf book when I type:

```s
$ make book/ggplot2-book.pdf
```

This is my first time using make, so improvements/pointers are more than welcome :)

**Comment by mathomp4** [comment]
Question from someone interested in reading/helping with the book: where does one get the "bookdown" package that seems required by the make file:
```
(44)(master) $ make book/ggplot2-book.pdf 
Rscript render-tex.R qplot.rmd mastery.rmd scales.rmd position.rmd data.rmd polishing.rmd layers.rmd introduction.rmd specifications.rmd translating.rmd toolbox.rmd duplication.rmd grid.rmd
Error in library("bookdown") : there is no package called ‘bookdown’
Execution halted
make: *** [book/tex/./qplot.tex] Error 1
```
I've tried installing in R, but it can't seem to find it:
```
> install.packages("bookdown")
Installing package into ‘/home/USER/R/x86_64-redhat-linux-gnu-library/3.1’
(as ‘lib’ is unspecified)
Warning message:
package ‘bookdown’ is not available (for R version 3.1.2) 
```

**Comment by cpsievert** [comment]
https://github.com/hadley/bookdown

**Comment by mathomp4** [comment]
Ah. Okay. Thanks. 

And now I know how to install a package on github!

**Comment by hadley** [comment]
@cpsievert could you add a note about that too the README too please?

**Comment by cpsievert** [comment]
Done!

**Comment by mathomp4** [comment]
You might also want to add a mention of a dependency to pandoc. I'm still trying to work to get that done.(Fun with RHEL 6...it has the old version of pandoc.)

**Comment by cpsievert** [comment]
Good point. 

RStudio bundles pandoc so you could try building inside RStudio (with ctrl+shift+b) if you're having troubles installing pandoc

@hadley do you want to add a note about pandoc in the README?

**Comment by mathomp4** [comment]
Hmm. @cpsievert really? I'll check when I get back to my Linux box tomorrow (I gave up on TexLive on my Mac...so much space used...).

Last time I tried to build in RStudio on Linux, the Build process essentially said something was up to date. (I could get farther using make on the command line, which led to the too-old-pandoc call). When I tried to clean or clean-and-rebuild, it said there is no 'clean' target to call.

**Comment by cpsievert** [comment]
Yes, [as of version v0.98.932, pandoc is bundled with RStudio](http://blog.rstudio.org/2014/06/18/r-markdown-v2/)

I'm still learning make, but with the changes I've pushed tonight, things should be better (feel free to send pull requests). There is a clean target now, so if all else fails, you should be able to do:

```
$ make clean
$ make
```

**Comment by jflanaga** [comment]
Not sure whether I'm missing a package or not, but when I run `make`, I get the error 
```
No rule to make target 'figures', needed by book/tex/ggplot2-book.pd
```
 If I run

```
make clean
make
```
I get 
```
make: Rscript: No such file or directory   
make: *** [book/tex/data.tex] Error 1
```
I have pandoc 1.13.2, by the by.

**Comment by cpsievert** [comment]
Oops, sorry, can you pull down again and see if that fixes it? Thanks!

**Comment by cpsievert** [comment]
@hadley want to turn on Travis for this repo so we can have it run make?

**Comment by jflanaga** [comment]
I'm still have problems. I get a ton of error messages, then the fatal error: 

```
! LaTeX Error: File `figures/qplotqscatter-1' not found

```

I had the problem that I initially did not have Inconsolata installed. Not sure if that is related, but I think it should be.

**Comment by cpsievert** [comment]
Thanks. I've added Inconsolata to the README. I haven't been able to reproduce the error, but I'm guessing it's due to the omittance of `\DeclareGraphicsExtensions{.png,.pdf}` (especially if `"book/tex/figures/qplotqscatter-1.pdf"` exists -- that'd be great if you could check) which I've now included in 5a6f1bff64ba41eac1ee5303f48e1edc2cbbf043. Let me know if that fixes it!

**Comment by jflanaga** [comment]
Same error. No figures are being generated so the `figures`directory is empty (both in the root and in `book/tex/`

In addition, to install `captioner`, you need: 

`devtools::install_github("adletaw/captioner/captioner")`

My session info by the way is 

```
R version 3.1.1 (2014-07-10)
Platform: x86_64-apple-darwin13.1.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

```

**Comment by hadley** [comment]
@cpsievert it's on now!

**Comment by cpsievert** [comment]
@jflanaga in that case, you're probably running into an R error, which might be caused by a missing R package. I could be of more help if you share all the output.

**Comment by jflanaga** [comment]
Well, there isn't much more than saying 

```
LaTeX Warning: Reference `fig:diamond-dim' on page 12 undefined on input line 7
4.

<use  "diagrams/diamond-dimensions.pdf" > [12]

! LaTeX Error: File `figures/qplotqscatter-1' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.120 ...=0.49\linewidth]{figures/qplotqscatter-1}
                                                   \end{flushleft}
? 
```

Is there a list somewhere of all the packages needed for the book? I thought I had all of them, but that doesn't mean i was able to track it down. (I'm also having problems knitting any chapter that has `xtable()`. the error message I get for that (in the `qplot`chapter) is: 

```
Error in eval(expr, envir, enclos): could not find the function "xtable" calls: <Anonymous>. . . handle -> with CallingHandlers-> withVisible -> eval -> eval Execution halted

```

I do have `xtable` loaded, by the way.

**Comment by cpsievert** [comment]
LaTeX errors are irrelevant if the .Rmd files are not rendered properly. Please link to the output you see after typing `make` (or, at least, the contents of `"book/tex/render-log.txt"`) as a [gist](https://gist.github.com/).

The [.travis.yml](https://github.com/hadley/ggplot2-book/blob/master/.travis.yml) file will contain a list of all the R packages (it's currently a work in progress, though).

**Comment by jflanaga** [comment]
Hi, I hope I'm not being too much trouble. I'm just trying to figure out why this isn't working. But it is really for my own benefit rather than anything crucial, because I don't need a pdf. 

I could get the Rmd file to render if I added `library("xtable")` to the scripts where `xtable` is called (for 
instance, in the qplot chapter). I'm not 100% certain, but my guess is that the problem originated with commit 2c1c0a2, that is, the switch from `pander::pandoc.table` to `xtable` for the tables. 

Now, however, I have a different problem. After adding `library("xtable") to the `r qplot` chunk in the plot chapter and saving, I get the following error after running `make`: 

```
Rscript render-tex.R qplot.rmd
make: Rscript: No such file or directory
make: *** [book/tex/data.tex] Error 1

```
As I said, this is no big deal. I don't need the pdf. More my own curiosity.

**Comment by cpsievert** [comment]
Hmm, if you look at [render-tex.R](https://github.com/hadley/ggplot2-book/blob/master/render-tex.R), the xtable package is loaded so that we don't have to load it in each chapter individually.

Could you try starting over from scratch and reporting your output? Thanks!

```r
rm -r ggplot2-book
git clone  https://github.com/hadley/ggplot2-book.git
cd ggplot2-book
make
```

**Comment by jflanaga** [comment]
Will do sometime tomorrow. I'm not sure what the best practice might be, but personally I would want the package loaded in each chapter so I can knit that particular chapter (especially when it is still in development). I wouldn't want to make the entire book when all I want to do is see how changes affected a particular chapter. I can see making the change in the final version, but not before then. But maybe that's just me.

**Comment by cpsievert** [comment]
Eventually we may have 'standalone' chapters, but this is not very high on the TODO list. `make` is smart enough to only re-render chapters that have been updated, so you shouldn't need to render them using anything other than `make`.

**Comment by jflanaga** [comment]
Fair enough. The gist for the output when I run `make` in the terminal is located [here](https://gist.github.com/jflanaga/9b594dfda56cb2819fd9)

**Comment by cpsievert** [comment]
Thanks! I was able to replicate this error and resolve it by:

```
make clean
make
```

You shouldn't have to `make clean` in order to `make`. 1539f2665307598f07a050a8599a7f5ef5e8414c  should fix that.

**Comment by jflanaga** [comment]
Sorry to say this doesn't work for me (either `make` or `make clean` then `make`. 

Here's the output when I run `make clean`: 
`
rm -r book/tex
rm: book/tex: No such file or directory
make: *** [clean] Error 1
`

Here's the output when I run `make` after running `make clean`

```
mkdir book/tex
cp book/ggplot2-book.tex book/tex/ggplot2-book.tex
cp book/krantz.cls book/tex/krantz.cls
Rscript render-tex.R data.rmd duplication.rmd grid.rmd introduction.rmd layers.rmd mastery.rmd polishing.rmd position.rmd qplot.rmd scales.rmd specifications.rmd toolbox.rmd translating.rmd
make: Rscript: No such file or directory
make: *** [book/tex/data.tex] Error 1
```
And here's the output when I just run `make` from scratch: 

```
mkdir book/tex
cp book/ggplot2-book.tex book/tex/ggplot2-book.tex
cp book/krantz.cls book/tex/krantz.cls
touch ./data.rmd ./duplication.rmd ./grid.rmd ./introduction.rmd ./layers.rmd ./mastery.rmd ./polishing.rmd ./position.rmd ./qplot.rmd ./scales.rmd ./specifications.rmd ./toolbox.rmd ./translating.rmd
Rscript render-tex.R data.rmd duplication.rmd grid.rmd introduction.rmd layers.rmd mastery.rmd polishing.rmd position.rmd qplot.rmd scales.rmd specifications.rmd toolbox.rmd translating.rmd
make: Rscript: No such file or directory
make: *** [book/tex/data.tex] Error 1

```
And, yes, I deleted the local repo and started from scratch, with no difference.

**Comment by cpsievert** [comment]
Hmm, this is odd. `Rscript` runs without error [on TravisCI](https://travis-ci.org/hadley/ggplot2-book/builds/49246078) and on my mac, so it will be hard for me to identify the issue here. Could you try building from scratch one more time?

```
git clone https://github.com/hadley/ggplot2-book.git ggplot2-test
cd ggplot2-test
make
```

If you get that same error, open render-tex.R, comment out [this part](https://github.com/hadley/ggplot2-book/blob/1539f2665307598f07a050a8599a7f5ef5e8414c/render-tex.R#L40-42), replace it with `render_chapter("data.rmd")`, and see if that gives you a more informative error.

**Comment by jflanaga** [comment]
No, it didn't help, and the warning message isn't particularly more informative. I ran `make`, got the same error, commented out the part and added the alternative, then ran `make` again. Here's the output:

```
Rscript render-tex.R data.rmd duplication.rmd grid.rmd introduction.rmd layers.rmd mastery.rmd polishing.rmd position.rmd qplot.rmd scales.rmd specifications.rmd toolbox.rmd translating.rmd
make: Rscript: No such file or directory
make: *** [book/tex/data.tex] Error 1
```

I then started from scratch yet again, and instead of running `make` first, just commented out the lines and added `render_chapter("data.rmd")`. Here is what I got this time:

```
cp book/ggplot2-book.tex book/tex/ggplot2-book.tex
cp book/krantz.cls book/tex/krantz.cls
touch ./data.rmd ./duplication.rmd ./grid.rmd ./introduction.rmd ./layers.rmd ./mastery.rmd ./polishing.rmd ./position.rmd ./qplot.rmd ./scales.rmd ./specifications.rmd ./toolbox.rmd ./translating.rmd
Rscript render-tex.R data.rmd duplication.rmd grid.rmd introduction.rmd layers.rmd mastery.rmd polishing.rmd position.rmd qplot.rmd scales.rmd specifications.rmd toolbox.rmd translating.rmd
make: Rscript: No such file or directory
make: *** [book/tex/data.tex] Error 1
```

I haven't sat down and tried to figure out `make`, but I don't understand why I'm getting two different error messages  ¯\_(ツ)_/¯

If you can't duplicate the error and no on else is having these problems, then maybe it is just my system. I'm running OS 10.10.2, by the way, and I've already given the system info for R. It's not really all that much of an issue for me: I don't need the PDF, and I can just add the call for `xtable` package to the individual chapters if I want to knit them.

**Comment by eolembrain-leo** [comment]
Using RStudio (with ctrl+shift+b) to build, it shows the error message:

```
mkdir -p book/tex/figures && cp -r figures/* book/tex/figures
FIND: �ѼƮ榡�����T
cp: cannot stat `figures/*': No such file or directory
make: *** [book/tex/ggplot2-book.pdf] Error 1

Exited with status 2.
```

```
Session info ------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.0 (2015-04-16)
 system   i386, mingw32               
 ui       RStudio (0.99.435)          
 language (EN)                        
 collate  Chinese_Taiwan.950          
 tz       Asia/Taipei                 
```

**Comment by cpsievert** [comment]
Thanks for reporting @eolembrain-leo. I would try doing a "clean and rebuild"

![screen shot 2015-05-13 at 10 33 42 am](https://cloud.githubusercontent.com/assets/1365941/7614332/b9ebfefc-f95b-11e4-9f17-1a79e9a921dc.png)

You can also do that from the command line with

```
make clean
make
```

Let me know if that fixes it!

**Comment by eolembrain-leo** [comment]
Thanks a lot.
"clean and rebuild" method works!

However, it got stuck in outputting `translating.tex` for at least half an hour (and not finish yet).
I'm not sure if it's normal or an issue.

![image](https://cloud.githubusercontent.com/assets/8746961/7616311/0730fc24-f9d6-11e4-920f-8e18e7b57938.png)

**Comment by doughodson** [comment]
Looks like make is trying to use 'common.r', not 'common.R' -- I renamed everything proceeding much better.

**Comment by doughodson** [comment]
Not having any luck compiling book.  I believe I've installed all the packages needed, but now apparently getting errors in the book itself "Quitting from lines 400-404 (toolbox.rmd" and "Error in unit(tic_pos.c, "mm") : 'x' and 'units' must have length > 0"

**Comment by doughodson** [comment]
Observation: "Dynamic documents" are wonderful if documentation is tightly in sync with code, if not, documentation may no longer "compile" thus becomes useless.  Something interesting to consider.
